name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies
      run: yarn

    - name: Bundle
      # --dev false --minify true (?)
      run: yarn react-native bundle --entry-file index.js --platform android --assets-dest android/app/src/main/res --bundle-output android/app/src/main/assets/index.android.bundle

    - name: Build
      run: yarn react-native build-android

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: outputs
        path: android/app/build/outputs
