name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Create assets dir
      run: mkdir -p android/app/src/main/assets

    - name: Install dependencies
      run: yarn

    - name: Build
      run: yarn react-native build-android --mode=release

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: outputs
        path: android/app/build/outputs
